'use client';

import React, { useState } from 'react';
import { 
  ShieldCheck, Download, ExternalLink, X, Building2, User, FileCheck, AlertCircle, Copy, Check 
} from 'lucide-react';
import { LegalVerdict, FacilitatorDossier } from '@/types/domain';

interface FacilitatorModalProps {
  verdict: LegalVerdict;
  onClose: () => void;
}

export default function FacilitatorEscalationModal({ verdict, onClose }: FacilitatorModalProps) {
  const [applicantName, setApplicantName] = useState('');
  const [organization, setOrganization] = useState('');
  const [copied, setCopied] = useState(false);

  // Generate standardized Facilitation Dossier
  const dossier: FacilitatorDossier = {
    dossier_id: `AYUSH-IP-${Date.now().toString().slice(-6)}`,
    created_at: new Date().toISOString(),
    applicant_reference: applicantName ? `${applicantName} (${organization || 'Individual'})` : 'Confidential Innovator',
    original_query: verdict.query,
    jurisdiction: 'INDIA',
    verdict_title: verdict.verdict_title,
    is_patentable: verdict.is_patentable,
    resolved_botanicals: verdict.resolved_botanicals || [],
    statutory_bars: (verdict.reasoning_chain || []).map(step => ({
      section_code: step.citation?.citation_code || step.title,
      act_title: step.citation?.act_title || 'Indian Statutory Code',
      severity: step.severity,
      summary: step.description
    })),
    nba_compliance_needed: verdict.nba_approval_required,
    recommended_routes: (verdict.viable_routes || []).map(r => `${r.title}: ${r.description}`),
    patent_attorney_checklist: [
      verdict.nba_approval_required 
        ? 'Draft and submit Form III application to National Biodiversity Authority (NBA) prior to patent filing.'
        : 'Verify whether biological material is sourced exclusively from domestic registered cultivators.',
      'Evaluate whether composition qualifies as classical formulation listed in Ayurvedic Formulary of India (AFI).',
      'If seeking composition protection, prepare comparative in-vitro / clinical synergy data to overcome Section 3(e) / 3(d) objections.',
      'Assess eligibility for Process Patent on proprietary extraction or isolation protocol.',
      'Check availability of Trademark registration for brand identification and GI Tag linkage if geographically localized.'
    ],
    disclaimer: 'This dossier is an informational synthesis generated by IP-SAKTI Sahayak for transmission to a registered Indian Patent Agent or IP Facilitator under the Ministry of Ayush / Startup India Facilitation Scheme. It does not constitute formal legal representation.'
  };

  const generateMarkdownDossier = () => {
    return `# AYUSH IP FACILITATION DOSSIER
**Dossier Reference:** ${dossier.dossier_id}  
**Date of Assessment:** ${new Date(dossier.created_at).toLocaleDateString('en-IN', { dateStyle: 'full' })}  
**Applicant / Innovator:** ${dossier.applicant_reference}  
**Jurisdiction:** Indian Patents Act & Biological Diversity Regime  

---

## 1. Executive Formulation Summary
- **Original Claim / Query:** "${dossier.original_query}"
- **Preliminary Patentability Finding:** ${dossier.is_patentable ? 'CONDITIONALLY PATENTABLE (PROCESS / FORMULATION)' : 'PRODUCT PATENT BARRED UNDER SECTION 3'}
- **Verdict Classification:** ${dossier.verdict_title}
- **Mandatory NBA Approval Required:** ${dossier.nba_compliance_needed ? 'YES (Biological Diversity Act, 2002 Sec 6)' : 'NO'}

---

## 2. Botanical Taxonomy & Pharmacopoeial Mapping
${dossier.resolved_botanicals.map(b => `- **${b.sanskrit_name}** (${b.english_common_name}) → *${b.botanical_binomial}* [AFI Ref: ${b.afi_reference || 'Ayurvedic Pharmacopoeia'}]`).join('\n') || '- No specific botanical entities cataloged.'}

---

## 3. Statutory Bar Analysis & Citation Vault
${dossier.statutory_bars.map(sb => `### ${sb.section_code} — [${sb.severity}]
- **Act:** ${sb.act_title}
- **Findings:** ${sb.summary}
`).join('\n') || '- No active statutory objections flagged.'}

---

## 4. Recommended Viable Protection Strategies
${dossier.recommended_routes.map((r, i) => `${i + 1}. ${r}`).join('\n') || '- Further consultation with patent counsel recommended.'}

---

## 5. Patent Attorney & Facilitator Action Checklist
${dossier.patent_attorney_checklist.map(item => `- [ ] ${item}`).join('\n')}

---

*${dossier.disclaimer}*
`;
  };

  const handleDownload = () => {
    const mdContent = generateMarkdownDossier();
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${dossier.dossier_id}_IP_Facilitation_Dossier.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdownDossier());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="modal-overlay" onClick={onClose} style={{
      position: 'fixed',
      top: 0, left: 0, right: 0, bottom: 0,
      background: 'rgba(5, 8, 20, 0.85)',
      backdropFilter: 'blur(8px)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1000,
      padding: '1.5rem'
    }}>
      <div className="modal-content glass-panel" onClick={e => e.stopPropagation()} style={{
        maxWidth: '750px',
        width: '100%',
        maxHeight: '90vh',
        overflowY: 'auto',
        borderRadius: '16px',
        border: '1px solid rgba(16, 185, 129, 0.3)',
        background: '#0d1322',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.7)'
      }}>
        {/* Modal Header */}
        <div style={{
          padding: '1.5rem 2rem',
          borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          background: 'rgba(16, 185, 129, 0.05)'
        }}>
          <div className="flex items-center gap-3">
            <div style={{
              width: '40px', height: '40px', borderRadius: '10px',
              background: 'rgba(16, 185, 129, 0.2)',
              border: '1px solid var(--accent-emerald)',
              display: 'flex', alignItems: 'center', justifyContent: 'center'
            }}>
              <ShieldCheck className="text-emerald" size={24} />
            </div>
            <div>
              <h3 style={{ fontSize: '1.25rem', fontWeight: 700, color: 'white' }}>
                Human IP Facilitator Escalation
              </h3>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                Ministry of Ayush & Startup India IP Facilitation Protocol
              </p>
            </div>
          </div>
          <button onClick={onClose} style={{
            background: 'transparent', border: 'none', color: 'var(--text-secondary)',
            cursor: 'pointer', padding: '0.5rem', borderRadius: '8px'
          }}>
            <X size={20} />
          </button>
        </div>

        {/* Modal Body */}
        <div style={{ padding: '2rem' }}>
          <div style={{
            background: 'rgba(59, 130, 246, 0.1)',
            border: '1px solid rgba(59, 130, 246, 0.3)',
            borderRadius: '10px',
            padding: '1rem 1.25rem',
            marginBottom: '1.5rem',
            display: 'flex',
            gap: '1rem',
            alignItems: 'flex-start'
          }}>
            <AlertCircle size={20} className="text-blue" style={{ flexShrink: 0, marginTop: '2px' }} />
            <div style={{ fontSize: '0.85rem', color: '#93c5fd', lineHeight: 1.5 }}>
              <strong>Pre-Prosecution Handoff:</strong> This tool compiles your formulation evaluation into an official <strong>Ayush IP Facilitation Dossier</strong>. You can take this directly to a registered Patent Agent or Ministry of Ayush Facilitator for formal representation.
            </div>
          </div>

          {/* Optional Innovator Metadata */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
            <div>
              <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.4rem' }}>
                Innovator / Applicant Name (Optional)
              </label>
              <div style={{
                display: 'flex', alignItems: 'center', gap: '0.5rem',
                background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border-color)',
                borderRadius: '8px', padding: '0.5rem 0.75rem'
              }}>
                <User size={16} style={{ color: 'var(--text-secondary)' }} />
                <input 
                  type="text" 
                  value={applicantName}
                  onChange={e => setApplicantName(e.target.value)}
                  placeholder="e.g. Dr. A. Sharma"
                  style={{ background: 'transparent', border: 'none', color: 'white', outline: 'none', fontSize: '0.9rem', width: '100%' }}
                />
              </div>
            </div>

            <div>
              <label style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.4rem' }}>
                Entity / Institution (Optional)
              </label>
              <div style={{
                display: 'flex', alignItems: 'center', gap: '0.5rem',
                background: 'rgba(0,0,0,0.3)', border: '1px solid var(--border-color)',
                borderRadius: '8px', padding: '0.5rem 0.75rem'
              }}>
                <Building2 size={16} style={{ color: 'var(--text-secondary)' }} />
                <input 
                  type="text" 
                  value={organization}
                  onChange={e => setOrganization(e.target.value)}
                  placeholder="e.g. Ayush Biotech Lab"
                  style={{ background: 'transparent', border: 'none', color: 'white', outline: 'none', fontSize: '0.9rem', width: '100%' }}
                />
              </div>
            </div>
          </div>

          {/* Dossier Preview Summary */}
          <div style={{
            background: 'rgba(0, 0, 0, 0.4)',
            border: '1px solid var(--border-color)',
            borderRadius: '10px',
            padding: '1.25rem',
            marginBottom: '1.5rem'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
              <span style={{ fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--text-secondary)' }}>
                Dossier Identifier: <strong style={{ color: 'white' }}>{dossier.dossier_id}</strong>
              </span>
              <span className="status-badge" style={{
                background: verdict.is_patentable ? 'rgba(16, 185, 129, 0.2)' : 'rgba(239, 68, 68, 0.2)',
                color: verdict.is_patentable ? '#34d399' : '#f87171',
                fontSize: '0.75rem'
              }}>
                {verdict.is_patentable ? 'Process Viable' : 'Section 3(p) Barred'}
              </span>
            </div>

            <div style={{ fontSize: '0.9rem', color: 'white', fontWeight: 600, marginBottom: '0.5rem' }}>
              Claim: &ldquo;{verdict.query}&rdquo;
            </div>

            <div style={{ fontSize: '0.825rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
              <strong>Key Mandates:</strong> {verdict.nba_approval_required ? '⚠️ National Biodiversity Authority (NBA) Prior Approval Form III Mandatory' : '✓ Standard IPR Procedure'}
            </div>

            {/* Checklist */}
            <div style={{ fontSize: '0.8rem', color: '#cbd5e1' }}>
              <strong style={{ display: 'block', marginBottom: '0.4rem', color: 'var(--accent-emerald)' }}>
                Facilitator Immediate Checklist:
              </strong>
              <ul style={{ listStyle: 'none', padding: 0 }}>
                {dossier.patent_attorney_checklist.slice(0, 3).map((item, idx) => (
                  <li key={idx} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.3rem' }}>
                    <FileCheck size={14} className="text-emerald" /> {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Official Facilitation Channels */}
          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.5rem', fontWeight: 600 }}>
              Official Facilitation Directories:
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
              <a 
                href="https://ipindia.gov.in" 
                target="_blank" 
                rel="noreferrer"
                className="btn"
                style={{ fontSize: '0.8rem', padding: '0.6rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem', textDecoration: 'none' }}
              >
                IP India Registered Agents <ExternalLink size={14} />
              </a>
              <a 
                href="https://ayush.gov.in" 
                target="_blank" 
                rel="noreferrer"
                className="btn"
                style={{ fontSize: '0.8rem', padding: '0.6rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem', textDecoration: 'none' }}
              >
                Ministry of Ayush Facilitation Cell <ExternalLink size={14} />
              </a>
            </div>
          </div>

          {/* Action Buttons */}
          <div style={{ display: 'flex', gap: '1rem', justifyContent: 'flex-end' }}>
            <button 
              onClick={handleCopy} 
              className="btn" 
              style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem' }}
            >
              {copied ? <Check size={16} className="text-emerald" /> : <Copy size={16} />}
              {copied ? 'Copied Brief' : 'Copy Brief'}
            </button>
            <button 
              onClick={handleDownload} 
              className="btn btn-primary" 
              style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.875rem' }}
            >
              <Download size={16} /> Download Case Dossier (.md)
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
